version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: coffee-machine-db
    environment:
      POSTGRES_DB: coffee_machine_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d coffee_machine_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - coffee-machine-net

  coffee-machine-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffee-machine-service
    environment:
      DB_HOST: coffee-machine-db
      DB_PORT: 5432
      DB_COFFEE_MACHINE_NAME: coffee_machine_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - coffee-machine-net

networks:
  coffee-machine-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local