server:
  port: 8081

spring:
  application:
    name: coffee-machine-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coffee_machine_db
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 10

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jpa:
  show-sql: true
  hibernate:
    ddl-auto: validate

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

